import { getId } from '@/lib/utils/helper';

export const projectsSection = {
  title: 'Projects I have Worked On',
  // projects: [
  //   {
  //     id: getId(),
  //     name: 'easy fix',
  //     url: 'https://easy-fix.vercel.app/',
  //     repo: 'https://github.com/shoishob007/easy-fix',
  //     img: 'https://user-images.githubusercontent.com/68834718/258852895-df5c6da7-a698-40fb-97c3-a5474314cb85.png',
  //     year: 2023,
  //     tags: ['React', 'Tailwind'],
  //   },
  // ],

  projects: [
    {
      id: getId(),
      name: 'Demo Project 1',
      url: '#',
      repo: '#',
      img: '/demo-project.jpg',
      year: 2024,
      tags: ['Demo Tech', 'Demo Tech'],
    },
    {
      id: getId(),
      name: 'Demo Project 2',
      url: '#',
      repo: '#',
      img: '/demo-project.jpg',
      year: 2024,
      tags: ['Demo Tech', 'Demo Tech'],
    },
    {
      id: getId(),
      name: 'Demo Project 3',
      url: '#',
      repo: '#',
      img: '/demo-project.jpg',
      year: 2024,
      tags: ['Demo Tech', 'Demo Tech'],
    },
    {
      id: getId(),
      name: 'Demo Project 4',
      url: '#',
      repo: '#',
      img: '/demo-project.jpg',
      year: 2023,
      tags: ['Demo Tech', 'Demo Tech'],
    },
    {
      id: getId(),
      name: 'Demo Project 5',
      url: '#',
      repo: '#',
      img: '/demo-project.jpg',
      year: 2023,
      tags: ['Demo Tech', 'Demo Tech'],
    },
    {
      id: getId(),
      name: 'Demo Project 6',
      url: '#',
      repo: '#',
      img: '/demo-project.jpg',
      year: 2023,
      tags: ['Demo Tech', 'Demo Tech'],
    },
    {
      id: getId(),
      name: 'Demo Project 7',
      url: '#',
      repo: '#',
      img: '/demo-project.jpg',
      year: 2023,
      tags: ['Demo Tech', 'Demo Tech'],
    },
    {
      id: getId(),
      name: 'Demo Project 8',
      url: '#',
      repo: '#',
      img: '/demo-project.jpg',
      year: 2022,
      tags: ['Demo Tech', 'Demo Tech'],
    },
    {
      id: getId(),
      name: 'Demo Project 9',
      url: '#',
      repo: '#',
      img: '/demo-project.jpg',
      year: 2022,
      tags: ['Demo Tech', 'Demo Tech'],
    },
    {
      id: getId(),
      name: 'Demo Project 10',
      url: '#',
      repo: '#',
      img: '/demo-project.jpg',
      year: 2021,
      tags: ['Demo Tech', 'Demo Tech'],
    },
    {
      id: getId(),
      name: 'Demo Project 11',
      url: '#',
      repo: '#',
      img: '/demo-project.jpg',
      year: 2021,
      tags: ['Demo Tech', 'Demo Tech'],
    },
    {
      id: getId(),
      name: 'Demo Project 12',
      url: '#',
      repo: '#',
      img: '/demo-project.jpg',
      year: 2020,
      tags: ['Demo Tech', 'Demo Tech'],
    },
  ],
};
